nome = str(input('Digit seu nome completo:  ')) .strip()
nome1 = nome.split()
print('Muito prazer em te conhecer!')
print('Seu primeiro nome é {}.' .format(nome1[0]))
print('Seu ultimo nome é {}' .format(nome1[len(nome1)-1]))
